### ISSUE TITLE
Does not parse Apple Holiday ICS feed using `initUrl()`

### ISSUE THREAD

**Issue by yabdab** [u01jmg3/ics-parser#183]
### Description of the Issue:

Does not find any events when using Apple's public Holiday ICS feed?

https://p41-calendars.icloud.com/holidays/us_en-us.ics

**Comment by u01jmg3** [comment]
If you download the calendar manually, the parser will read it without issue.

However, if you attempt to parse the feed using `$ical->initUrl('https://p41-calendars.icloud.com/holidays/us_en-us.ics')` it does not return any events as you have found. This is because iCloud forces the ICS file to be downloaded and PHP's [`file()` function](https://secure.php.net/manual/en/function.file.php) is unable to retrieve it. I tried switching to cURL but ran into the same issue.

I would therefore suggest automating downloading the ICS file locally before attempting to parse it.

**Comment by u01jmg3** [comment]
Closing as explanation given. Happy to reopen if further discussion is required.
