### ISSUE TITLE
Support ability to parse CATEGORIES

### ISSUE THREAD

**Issue by BenWaNH** [u01jmg3/ics-parser#313]
Hi!

Not a bug but,
Is there a way to parse with CATEGORIES prop?

https://www.kanzaki.com/docs/ical/categories.html

Thanks

**Comment by u01jmg3** [comment]
Not currently but happy to accept a PR.

**Comment by room34** [comment]
I'm curious what you're looking for here. In my experience ics-parser does already handle the CATEGORIES property; the problem is that many of the big source calendar applications (Google Calendar, Office 365) do not include any CATEGORIES data in the .ics feed in the first place. But, if CATEGORIES is in the feed, it's showing up properly in the parsed data for me.
