### ISSUE TITLE
eventsFromRange fails: Cannot use object of type ICal\EventObject as array

### ISSUE THREAD

**Issue by ChrisLamprecht** [u01jmg3/ics-parser#89]
`$ical->events()` works fine, but `$ical->eventsFromRange()` fails with:

`FatalThrowableError` in `ICal.php` line `1060`:
Cannot use object of type `ICal\EventObject` as array

?

**Comment by u01jmg3** [comment]
- First of all, can I check you are using the latest version of this library (`dev-master`)?
- Secondly, what iCal snippet are you attempting to parse?
  - I need to know exactly what you are doing in order to replicate your problem. The example page uses [`eventsFromRange()`](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L35) and for me has no issue parsing events from March through April.

**Comment by ChrisLamprecht** [comment]
Sorry for the late reply... I used the latest version, but in the meantime I can't remember which .ics file I tried... Now I store all vevents in a table do the rest with sql... thank you! :-)
